# Generated by Django 6.0.5 on 2026-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='Número de Serial')),
                ('inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo / Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DEBAJA', 'Dado de Baja'), ('ALMACENADO', 'En Almacén')], default='ACTIVO', max_length=20, verbose_name='Estado actual')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
    ]
