# Generated by Django 6.0.5 on 2026-05-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('correo', models.CharField(max_length=100, unique=True, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100, unique=True, verbose_name='Ubicación')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='accesorios',
            field=models.CharField(default=2, max_length=50, verbose_name='Accesorios'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.equipo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.empleados')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.ubicacion'),
        ),
    ]
