# Generated by Django 6.0.5 on 2026-05-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_empleados_ubicacion_equipo_accesorios_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
