# Generated by Django 6.0.5 on 2026-05-21 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_empleados_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_devolucion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de devolucion'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
    ]
