# Generated by Django 6.0.5 on 2026-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_asignacion_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Equipo'),
        ),
    ]
