# Generated by Django 6.0.5 on 2026-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_equipo_modelo_alter_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='inventario',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Inventario'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serial'),
        ),
    ]
